theme: jekyll-theme-minimal
title: Emberlight Interactive
author: Tristan Mastrodicasa
description: Toronto based game studio
navbar-links:
  Privacy Policy: "privacy-policy"
avatar: "/da-flame.png"

timezone: "America/Toronto"