theme: jekyll-theme-minimal
logo: "/da-flame.png"
title: Emberlight Interactive
author: Tristan Mastrodicasa
description: Toronto based game studio
navbar-links:
  Privacy Policy: "privacy-policy"

timezone: "America/Toronto"